#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...schema_config.json_scalar import custom_scalars
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from gql_client.runtime.enum_utils import enum_field_metadata
from ..enum.agent import Agent


@dataclass(frozen=True)
class Turn(DataClassJsonMixin):
    agent: Optional[Agent] = None
    said: Optional[str] = None
