from typing import List, Optional, BinaryIO
from gql.client import Client
from .api.sensibility import sensibility as _sensibility
from .api.sentiment import sentiment as _sentiment
from .api.similarity import similarity as _similarity
from .api.topics import topics as _topics
from .api.input.turn import Turn
from .api.enum.relation import Relation

class GraphqlClient(Client):
    def answer(self, input: str, context: str) -> str: ...
    def chitchat(self, input: str, history: List[Turn] = []) -> str: ...
    def choose(self, input: str, context: str, choices: List[str] = []) -> str: ...
    def dialogact(self, input: str) -> str: ...
    def paraphrase(self, input: str) -> List[str]: ...
    def relations(self, input: str, relation: Relation) -> List[str]: ...
    def sensibility(
        self, input: List[str] = [], history: List[Turn] = []
    ) -> List[_sensibility.sensibilityData.SensibilityResult.DialogAlternative]: ...
    def sentiment(
        self, input: str
    ) -> List[_sentiment.sentimentData.SentimentResult.SentimentAnalysis]: ...
    def similarity(
        self, input: str, candidates: List[str] = []
    ) -> Optional[List[_similarity.similarityData.SimilarityResult.PairSimilarity]]: ...
    def speak(self, input: str, output: BinaryIO) -> None: ...
    def topics(
        self,
        input: Optional[str] = None,
        allow_multiple: Optional[bool] = None,
        topics: List[str] = [],
    ) -> List[_topics.topicsData.TopicsResult.TopicScore]: ...
    def transcribe(self, input: BinaryIO) -> str: ...
