#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from ..schema_config.json_scalar import custom_scalars
from gql_client.runtime.variables import encode_variables
from gql import gql, Client
from gql.transport.exceptions import TransportQueryError
from functools import partial
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional
from time import perf_counter
from dataclasses_json import DataClassJsonMixin, config

from gql_client.runtime.enum_utils import enum_field_metadata
from .enum.a_c_e_output_type import ACEOutputType


# fmt: off
QUERY: List[str] = ["""
query parseACE($input: String!, $type: ACEOutputType!) {
  result: callParseACE(input: $input, type: $type) {
    parsed: result
  }
}

"""
]


class parseACE:
    @dataclass(frozen=True)
    class parseACEData(DataClassJsonMixin):
        @dataclass(frozen=True)
        class ACEResult(DataClassJsonMixin):
            parsed: Optional[str]

        result: Optional[ACEResult]

    # fmt: off
    @classmethod
    def execute(cls, client: Client, input: str, type: ACEOutputType) -> Optional[parseACEData.ACEResult]:
        variables: Dict[str, Any] = {"input": input, "type": type}
        new_variables = encode_variables(variables, custom_scalars)
        response_text = client.execute(
            gql("".join(set(QUERY))), variable_values=new_variables
        )
        res = cls.parseACEData.from_dict(response_text)
        return res.result

    # fmt: off
    @classmethod
    async def execute_async(cls, client: Client, input: str, type: ACEOutputType) -> Optional[parseACEData.ACEResult]:
        variables: Dict[str, Any] = {"input": input, "type": type}
        new_variables = encode_variables(variables, custom_scalars)
        response_text = await client.execute_async(
            gql("".join(set(QUERY))), variable_values=new_variables
        )
        res = cls.parseACEData.from_dict(response_text)
        return res.result
