#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from ..schema_config.json_scalar import custom_scalars
from gql_client.runtime.variables import encode_variables
from gql import gql, Client
from gql.transport.exceptions import TransportQueryError
from functools import partial
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional
from time import perf_counter
from dataclasses_json import DataClassJsonMixin, config

from .input.turn import Turn


# fmt: off
QUERY: List[str] = ["""
query sensibility($input: [String!]!, $history: [Turn!]!) {
  callSensibility(input: $input, history: $history) {
    result {
      alternative
      score
    }
  }
}

"""
]


class sensibility:
    @dataclass(frozen=True)
    class sensibilityData(DataClassJsonMixin):
        @dataclass(frozen=True)
        class SensibilityResult(DataClassJsonMixin):
            @dataclass(frozen=True)
            class DialogAlternative(DataClassJsonMixin):
                alternative: str
                score: Number

            result: List[DialogAlternative]

        callSensibility: SensibilityResult

    # fmt: off
    @classmethod
    def execute(cls, client: Client, input: List[str] = [], history: List[Turn] = []) -> sensibilityData.SensibilityResult:
        variables: Dict[str, Any] = {"input": input, "history": history}
        new_variables = encode_variables(variables, custom_scalars)
        response_text = client.execute(
            gql("".join(set(QUERY))), variable_values=new_variables
        )
        res = cls.sensibilityData.from_dict(response_text)
        return res.callSensibility

    # fmt: off
    @classmethod
    async def execute_async(cls, client: Client, input: List[str] = [], history: List[Turn] = []) -> sensibilityData.SensibilityResult:
        variables: Dict[str, Any] = {"input": input, "history": history}
        new_variables = encode_variables(variables, custom_scalars)
        response_text = await client.execute_async(
            gql("".join(set(QUERY))), variable_values=new_variables
        )
        res = cls.sensibilityData.from_dict(response_text)
        return res.callSensibility
