#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class Agent(Enum):
    BOT = "BOT"
    USER = "USER"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "Agent":
        return cls.MISSING_ENUM
