#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class Category(Enum):
    oEffect = "oEffect"
    oReact = "oReact"
    oWant = "oWant"
    xAttr = "xAttr"
    xEffect = "xEffect"
    xIntent = "xIntent"
    xNeed = "xNeed"
    xReact = "xReact"
    xWant = "xWant"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "Category":
        return cls.MISSING_ENUM
