#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from enum import Enum


class Relation(Enum):
    AtLocation = "AtLocation"
    CapableOf = "CapableOf"
    Causes = "Causes"
    CausesDesire = "CausesDesire"
    CreatedBy = "CreatedBy"
    DefinedAs = "DefinedAs"
    DesireOf = "DesireOf"
    Desires = "Desires"
    HasA = "HasA"
    HasFirstSubevent = "HasFirstSubevent"
    HasLastSubevent = "HasLastSubevent"
    HasPainCharacter = "HasPainCharacter"
    HasPainIntensity = "HasPainIntensity"
    HasPrerequisite = "HasPrerequisite"
    HasProperty = "HasProperty"
    HasSubevent = "HasSubevent"
    InheritsFrom = "InheritsFrom"
    InstanceOf = "InstanceOf"
    IsA = "IsA"
    LocatedNear = "LocatedNear"
    LocationOfAction = "LocationOfAction"
    MadeOf = "MadeOf"
    MotivatedByGoal = "MotivatedByGoal"
    NotCapableOf = "NotCapableOf"
    NotDesires = "NotDesires"
    NotHasA = "NotHasA"
    NotHasProperty = "NotHasProperty"
    NotIsA = "NotIsA"
    NotMadeOf = "NotMadeOf"
    PartOf = "PartOf"
    ReceivesAction = "ReceivesAction"
    RelatedTo = "RelatedTo"
    SymbolOf = "SymbolOf"
    UsedFor = "UsedFor"
    MISSING_ENUM = ""

    @classmethod
    def _missing_(cls, value: object) -> "Relation":
        return cls.MISSING_ENUM
